defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: 'About us'
propagationMethod: all
siteSettings:
  ffabebe0-14cb-41b6-bdff-dc57cc98372a: # Craft Training
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: about-us
type: single
