defaultPlacement: end
enableVersioning: true
handle: contactUs
name: 'Contact us'
propagationMethod: all
siteSettings:
  ffabebe0-14cb-41b6-bdff-dc57cc98372a: # Craft Training
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: contact
type: single
