defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  ffabebe0-14cb-41b6-bdff-dc57cc98372a: # Craft Training
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
